package servlet.user.view;

import servlet.constants.SearchConstants;
import servlet.dao.CategoryDAO;
import servlet.dao.impl.CategoryDAOImpl;
import servlet.models.Category;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

@WebServlet("/public/header-view")
public class HeaderView extends HttpServlet {

    private static final long serialVersionUID = 1L;
    private static String productSearchUrl = "../public/shop";
    private CategoryDAO categoryDAO;

    public HeaderView() {
        super();
        categoryDAO = new CategoryDAOImpl();
    }

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {

        resp.setContentType("text/html; charset=UTF-8");
        resp.setCharacterEncoding("UTF-8");
        PrintWriter out = resp.getWriter();

        List<Category> categories = categoryDAO.findAll(1000, 1, "category_id", SearchConstants.DEFAULT_DIR, null, 1);

        out.append("<!doctype html>");
        out.append("<html class=\"no-js\" lang=\"zxx\">");
        out.append("    ");
        out.append("<head>");
        out.append("        <meta charset=\"utf-8\">");
        out.append("        <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">");
        out.append("        <title>Vue - Clean Minimal eCommerce HTML Template</title>");
        out.append("        <meta name=\"description\" content=\"\">");
        out.append("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
        out.append("");
        out.append("		<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"../user/../user/img/favicon.png\">");
        out.append("        <!-- Place favicon.ico in the root directory -->");
        out.append("");
        out.append("		<!-- CSS here -->");
        out.append("        <link rel=\"stylesheet\" href=\"../user/css/bootstrap.min.css\">");
        out.append("        <link rel=\"stylesheet\" href=\"../user/css/owl.carousel.min.css\">");
        out.append("        <link rel=\"stylesheet\" href=\"../user/css/animate.min.css\">");
        out.append("        <link rel=\"stylesheet\" href=\"../user/css/magnific-popup.css\">");
        out.append("        <link rel=\"stylesheet\" href=\"../user/css/fontawesome-all.min.css\">");
        out.append("        <link rel=\"stylesheet\" href=\"../user/css/flaticon.css\">");
        out.append("        <link rel=\"stylesheet\" href=\"../user/css/meanmenu.css\">");
        out.append("        <link rel=\"stylesheet\" href=\"../user/css/meanmenu.css\">");
        out.append("        <link rel=\"stylesheet\" href=\"../user/css/slick.css\">");
        out.append("        <link rel=\"stylesheet\" href=\"../user/css/default.css\">");
        out.append("        <link rel=\"stylesheet\" href=\"../user/css/style.css\">");
        out.append("        <link rel=\"stylesheet\" href=\"../user/css/responsive.css\">");
        out.append("    </head>");
        out.append("    <body>");
        out.append("");
        out.append("");
        out.append("        <!-- preloader -->");
        out.append("        <div id=\"preloader\">");
        out.append("            <div class=\"preloader\">");
        out.append("                <span></span>");
        out.append("                <span></span>");
        out.append("            </div>");
        out.append("        </div>");
        out.append("        <!-- preloader end  -->");
        out.append("");
        out.append("        <!-- header start -->");
        out.append("        <header>");
        out.append("            <div id=\"header-sticky\" class=\"header-area box-90\">");
        out.append("                <div class=\"container-fluid\">");
        out.append("                    <div class=\"row align-items-center\">");
        out.append("                        <div class=\"col-xl-2 col-lg-6 col-md-6 col-7 col-sm-5 d-flex align-items-center pos-relative\">");
        out.append("                            <div class=\"basic-bar cat-toggle\">");
        out.append("                                <span class=\"bar1\"></span>");
        out.append("                                <span class=\"bar2\"></span>");
        out.append("                                <span class=\"bar3\"></span>");
        out.append("                            </div>");
        out.append("                            <div class=\"logo\">");
        out.append("                                <a href=\"index.html\"><img src=\"../user/img/logo/logo.png\" alt=\"\"></a>");
        out.append("                            </div>");
        out.append("");
        out.append("                            <div class=\"category-menu\">");
        out.append("                                <h4>Category</h4>");
        out.append("                                <ul>");
        out.append("                                    <li><a href=\"shop.html\"><i class=\"flaticon-shopping-cart-1\"></i> Table lamp</a></li>");
        out.append("                                    <li><a href=\"shop.html\"><i class=\"flaticon-shopping-cart-1\"></i> Furniture</a></li>");
        out.append("                                    <li><a href=\"shop.html\"><i class=\"flaticon-shopping-cart-1\"></i> Chair</a></li>");
        out.append("                                    <li><a href=\"shop.html\"><i class=\"flaticon-shopping-cart-1\"></i> Men</a></li>");
        out.append("                                    <li><a href=\"shop.html\"><i class=\"flaticon-shopping-cart-1\"></i> Women</a></li>");
        out.append("                                    <li><a href=\"shop.html\"><i class=\"flaticon-shopping-cart-1\"></i> Cloth</a></li>");
        out.append("                                    <li><a href=\"shop.html\"><i class=\"flaticon-shopping-cart-1\"></i> Trend</a></li>");
        out.append("                                </ul>");
        out.append("                            </div>");
        out.append("                        </div>");
        out.append("                        <div class=\"col-xl-8 col-lg-6 col-md-8 col-8 d-none d-xl-block\">");
        out.append("                            <div class=\"main-menu text-center\">");
        out.append("                                <nav id=\"mobile-menu\">");
        out.append("                                    <ul>");
        out.append("                                        <li>");
        out.append("                                            <a href=\"../public/home\">Trang chủ</a>");
        out.append("                                        </li>");
        out.append("                                        <li>");
        out.append("                                            <a href=\"../public/shop\">Cửa hàng</a>");
        out.append("                                        </li>");
        out.append("                                        <li class=\"mega-menu\">");
        out.append("                                            <a href=\"#\">Sản phẩm </a>");
        out.append("											<ul class=\"submenu \">");
        out.append("                                                <li>");
        out.append("                                                    <a href=\"#\">Danh mục sản phẩm</a>");
        out.append("                                                    <ul class=\"submenu  level-1\">");
        categories.forEach(category -> {
            out.append("                                                        <li>");
            out.append("                                                            <a href=\""+ (productSearchUrl + "?category=" + category.getCategoryId())+"\">"+category.getCategoryName()+"</a>");
            out.append("                                                        </li>");
        });
        out.append("                                                    </ul>");
        out.append("                                                </li>");
        out.append("                                                <li>");
        out.append("                                                    <a href=\"#\">Chất liệu</a>");
        out.append("                                                    <ul class=\"submenu\">");
        out.append("                                                        <li>");
        out.append("                                                            <a href=\"shop-left-sidebar.html\">Sidebar Left</a>");
        out.append("                                                        </li>");
        out.append("                                                        <li>");
        out.append("                                                            <a href=\"shop-sidebar-right.html\">Sidebar Right</a>");
        out.append("                                                        </li>");
        out.append("                                                        <li>");
        out.append("                                                            <a href=\"cart.html\">Shopping Cart</a>");
        out.append("                                                        </li>");
        out.append("                                                        <li>");
        out.append("                                                            <a href=\"checkout.html\">Checkout</a>");
        out.append("                                                        </li>");
        out.append("                                                        <li>");
        out.append("                                                            <a href=\"wishlist.html\">My Wishlist</a>");
        out.append("                                                        </li>");
        out.append("                                                    </ul>");
        out.append("                                                </li>");
        out.append("                                                <li>");
        out.append("                                                    <a href=\"#\">Products Types</a>");
        out.append("                                                    <ul class=\"submenu\">");
        out.append("                                                        <li>");
        out.append("                                                            <a href=\"product-simple.html\">Simple Product</a>");
        out.append("                                                        </li>");
        out.append("                                                        <li>");
        out.append("                                                            <a href=\"product-variable.html\">Variable Product</a>");
        out.append("                                                        </li>");
        out.append("                                                        <li>");
        out.append("                                                            <a href=\"product-upcoming.html\">Product Upcoming</a>");
        out.append("                                                        </li>");
        out.append("                                                        <li>");
        out.append("                                                            <a href=\"product-up-thumb.html\">Thumb Top Product</a>");
        out.append("                                                        </li>");
        out.append("                                                        <li>");
        out.append("                                                            <a href=\"product-sidebar.html\">Product Sidebar</a>");
        out.append("                                                        </li>");
        out.append("                                                    </ul>");
        out.append("                                                </li>");
        out.append("                                            </ul>");
        out.append("                                        </li>");
        out.append("                                        <li>");
        out.append("                                            <a href=\"../public/blog\">Tin tức</a>");
        out.append("                                        </li>");
        out.append("                                        <li>");
        out.append("                                            <a href=\"../public/introduction\">Giới thiệu</a>");
        out.append("                                        </li>");
        out.append("                                        <li>");
        out.append("                                            <a href=\"../public/contact\">Liên hệ</a>");
        out.append("                                        </li>");
        out.append("                                    </ul>");
        out.append("                                </nav>");
        out.append("                            </div>");
        out.append("                        </div>");
        out.append("                        <div class=\"col-xl-2 col-lg-6 col-md-6 col-5 col-sm-7 pl-0\">");
        out.append("                            <div class=\"header-right f-right\">");
        out.append("                                <ul>");
        out.append("                                    <li class=\"search-btn\">");
        out.append("                                        <a class=\"search-btn nav-search search-trigger\" href=\"#\"><i class=\"fas fa-search\"></i></a>");
        out.append("                                    </li>");
        out.append("                                    <li class=\"login-btn\"><a href=\"../public/login\"><i class=\"far fa-user\"></i></a></li>");
        out.append("                                    <li class=\"d-shop-cart\"><a href=\"#\"><i class=\"flaticon-shopping-cart\"></i> <span class=\"cart-count\">3</span></a>");
        out.append("                                        <ul class=\"minicart\">");
        out.append("                                            <li>");
        out.append("                                                <div class=\"cart-img\">");
        out.append("                                                    <a href=\"product-details.html\">");
        out.append("                                                        <img src=\"../user/img/product/pro1.jpg\" alt=\"\" />");
        out.append("                                                    </a>");
        out.append("                                                </div>");
        out.append("                                                <div class=\"cart-content\">");
        out.append("                                                    <h3>");
        out.append("                                                        <a href=\"product-details.html\">Black & White Shoes</a>");
        out.append("                                                    </h3>");
        out.append("                                                    <div class=\"cart-price\">");
        out.append("                                                        <span class=\"new\">$ 229.9</span>");
        out.append("                                                        <span>");
        out.append("                                                            <del>$239.9</del>");
        out.append("                                                        </span>");
        out.append("                                                    </div>");
        out.append("                                                </div>");
        out.append("                                                <div class=\"del-icon\">");
        out.append("                                                    <a href=\"#\">");
        out.append("                                                        <i class=\"far fa-trash-alt\"></i>");
        out.append("                                                    </a>");
        out.append("                                                </div>");
        out.append("                                            </li>");
        out.append("                                            <li>");
        out.append("                                                <div class=\"cart-img\">");
        out.append("                                                    <a href=\"product-details.html\">");
        out.append("                                                        <img src=\"../user/img/product/pro2.jpg\" alt=\"\" />");
        out.append("                                                    </a>");
        out.append("                                                </div>");
        out.append("                                                <div class=\"cart-content\">");
        out.append("                                                    <h3>");
        out.append("                                                        <a href=\"product-details.html\">Black & White Shoes</a>");
        out.append("                                                    </h3>");
        out.append("                                                    <div class=\"cart-price\">");
        out.append("                                                        <span class=\"new\">$ 229.9</span>");
        out.append("                                                        <span>");
        out.append("                                                            <del>$239.9</del>");
        out.append("                                                        </span>");
        out.append("                                                    </div>");
        out.append("                                                </div>");
        out.append("                                                <div class=\"del-icon\">");
        out.append("                                                    <a href=\"#\">");
        out.append("                                                        <i class=\"far fa-trash-alt\"></i>");
        out.append("                                                    </a>");
        out.append("                                                </div>");
        out.append("                                            </li>");
        out.append("                                            <li>");
        out.append("                                                <div class=\"cart-img\">");
        out.append("                                                    <a href=\"product-details.html\">");
        out.append("                                                        <img src=\"../user/img/product/pro3.jpg\" alt=\"\" />");
        out.append("                                                    </a>");
        out.append("                                                </div>");
        out.append("                                                <div class=\"cart-content\">");
        out.append("                                                    <h3>");
        out.append("                                                        <a href=\"product-details.html\">Black & White Shoes</a>");
        out.append("                                                    </h3>");
        out.append("                                                    <div class=\"cart-price\">");
        out.append("                                                        <span class=\"new\">$ 229.9</span>");
        out.append("                                                        <span>");
        out.append("                                                            <del>$239.9</del>");
        out.append("                                                        </span>");
        out.append("                                                    </div>");
        out.append("                                                </div>");
        out.append("                                                <div class=\"del-icon\">");
        out.append("                                                    <a href=\"#\">");
        out.append("                                                        <i class=\"far fa-trash-alt\"></i>");
        out.append("                                                    </a>");
        out.append("                                                </div>");
        out.append("                                            </li>");
        out.append("                                            <li>");
        out.append("                                                <div class=\"total-price\">");
        out.append("                                                    <span class=\"f-left\">Total:</span>");
        out.append("                                                    <span class=\"f-right\">$300.0</span>");
        out.append("                                                </div>");
        out.append("                                            </li>");
        out.append("                                            <li>");
        out.append("                                                <div class=\"checkout-link\">");
        out.append("                                                    <a href=\"cart.html\">Shopping Cart</a>");
        out.append("                                                    <a class=\"red-color\" href=\"checkout.html\">Checkout</a>");
        out.append("                                                </div>");
        out.append("                                            </li>");
        out.append("                                        </ul>");
        out.append("                                    </li>");
        out.append("                                </ul>");
        out.append("                            </div>");
        out.append("                        </div>");
        out.append("                        <div class=\"col-12 d-xl-none\">");
        out.append("                            <div class=\"mobile-menu\"></div>");
        out.append("                        </div>");
        out.append("                    </div>");
        out.append("                </div>");
        out.append("            </div>");
        out.append("        </header>");
        out.append("        <!-- header end -->");
    }

    @Override
    protected void doPut(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        super.doPut(req, resp);
    }
}
