package servlet.user.view;

import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;


@WebServlet("/customer/checkout")
public class UserCheckoutView extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    
    public UserCheckoutView() {
        super();

    }

	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

		response.setContentType("text/html;charset=UTF-8");
		request.setCharacterEncoding("UTF-8");

		HttpSession session = request.getSession();
		if(session.getAttribute("customer") == null) {
			response.sendRedirect("../public/login");
			return;
		}

		PrintWriter out = response.getWriter();
		RequestDispatcher headerDispatcher = request.getRequestDispatcher("/public/header-view");
		headerDispatcher.include(request, response);

		out.append("<main>");
		out.append("");
		out.append("        <!-- breadcrumb-area-start -->");
		out.append("        <section class=\"breadcrumb-area\" data-background=\"img/bg/page-title.png\">");
		out.append("            <div class=\"container\">");
		out.append("                <div class=\"row\">");
		out.append("                    <div class=\"col-xl-12\">");
		out.append("                        <div class=\"breadcrumb-text text-center\">");
		out.append("                            <h1>Thanh toán</h1>");
		out.append("                            <ul class=\"breadcrumb-menu\">");
		out.append("                                <li><a href=\"index.html\">TRANG CHỦ</a></li>");
		out.append("                                <li><span>THANH TOÁN</span></li>");
		out.append("                            </ul>");
		out.append("                        </div>");
		out.append("                    </div>");
		out.append("                </div>");
		out.append("            </div>");
		out.append("        </section>");
		out.append("        <!-- breadcrumb-area-end -->");
		out.append("");
		out.append("        <!-- coupon-area start -->");
		out.append("        <section class=\"coupon-area pt-100 pb-30\">");
		out.append("            <div class=\"container\">");
		out.append("                <div class=\"row\">");
		out.append("                    <div class=\"col-md-6\">");
		out.append("                        <div class=\"coupon-accordion\">");
		out.append("                            <!-- ACCORDION START -->");
		out.append("                            <h3>Bạn đã có tài khoản? <span id=\"showlogin\">Đăng nhập</span></h3>");
		out.append("                            <div id=\"checkout-login\" class=\"coupon-content\">");
		out.append("                                <div class=\"coupon-info\">");
		out.append("                                    <p class=\"coupon-text\">Chúng tôi cam kết mang đến trải nghiệm mua sắm thuận tiện và dễ dàng cho bạn. Mọi quy trình được thiết kế tối ưu nhằm đảm bảo sự hài lòng của quý khách.</p>");
		out.append("                                    <form action=\"#\">");
		out.append("                                        <p class=\"form-row-first\">");
		out.append("                                            <label>Tên đăng nhập hoặc email <span class=\"required\">*</span></label>");
		out.append("                                            <input type=\"text\" />");
		out.append("                                        </p>");
		out.append("                                        <p class=\"form-row-last\">");
		out.append("                                            <label>Mật khẩu <span class=\"required\">*</span></label>");
		out.append("                                            <input type=\"text\" />");
		out.append("                                        </p>");
		out.append("                                        <p class=\"form-row\">");
		out.append("                                            <button class=\"btn theme-btn\" type=\"submit\">Đăng nhập</button>");
		out.append("                                            <label>");
		out.append("                                                <input type=\"checkbox\" />");
		out.append("                                                Nhớ mật khẩu");
		out.append("                                            </label>");
		out.append("                                        </p>");
		out.append("                                        <p class=\"lost-password\">");
		out.append("                                            <a href=\"#\">Quên mật khẩu?</a>");
		out.append("                                        </p>");
		out.append("                                    </form>");
		out.append("                                </div>");
		out.append("                            </div>");
		out.append("                            <!-- ACCORDION END -->");
		out.append("                        </div>");
		out.append("                    </div>");
		out.append("                    <div class=\"col-md-6\">");
		out.append("                        <div class=\"coupon-accordion\">");
		out.append("                            <!-- ACCORDION START -->");
		out.append("                            <h3>Bạn có mã ưu đãi? <span id=\"showcoupon\">Nhấn để nhập mã</span></h3>");
		out.append("                            <div id=\"checkout_coupon\" class=\"coupon-checkout-content\">");
		out.append("                                <div class=\"coupon-info\">");
		out.append("                                    <form action=\"#\">");
		out.append("                                        <p class=\"checkout-coupon\">");
		out.append("                                            <input type=\"text\" placeholder=\"Mã ưu đãi\" />");
		out.append("                                            <button class=\"btn theme-btn\" type=\"submit\">Áp dụng</button>");
		out.append("                                        </p>");
		out.append("                                    </form>");
		out.append("                                </div>");
		out.append("                            </div>");
		out.append("                            <!-- ACCORDION END -->");
		out.append("                        </div>");
		out.append("                    </div>");
		out.append("                </div>");
		out.append("            </div>");
		out.append("        </section>");
		out.append("        <!-- coupon-area end -->");
		out.append("        <!-- checkout-area start -->");
		out.append("        <section class=\"checkout-area pb-70\">");
		out.append("            <div class=\"container\">");
		out.append("                <form action=\"#\">");
		out.append("                    <div class=\"row\">");
		out.append("                        <div class=\"col-lg-6\">");
		out.append("                            <div class=\"checkbox-form\">");
		out.append("                                <h3>Thông tin thanh toán</h3>");
		out.append("                                <div class=\"row\">");
		out.append("                                    <div class=\"col-md-12\">");
		out.append("                                        <div class=\"country-select\">");
		out.append("                                            <label>Quốc gia <span class=\"required\">*</span></label>");
		out.append("                                            <select>");
		out.append("                                                <option value=\"volvo\">Việt Nam</option>");
		out.append("                                                <option value=\"saab\">Algeria</option>");
		out.append("                                                <option value=\"mercedes\">Afghanistan</option>");
		out.append("                                                <option value=\"audi\">Ghana</option>");
		out.append("                                                <option value=\"audi2\">Albania</option>");
		out.append("                                                <option value=\"audi3\">Bahrain</option>");
		out.append("                                                <option value=\"audi4\">Colombia</option>");
		out.append("                                                <option value=\"audi5\">Dominican Republic</option>");
		out.append("                                            </select>");
		out.append("                                        </div>");
		out.append("                                    </div>");
		out.append("                                    <div class=\"col-md-6\">");
		out.append("                                        <div class=\"checkout-form-list\">");
		out.append("                                            <label>Tên <span class=\"required\">*</span></label>");
		out.append("                                            <input type=\"text\" placeholder=\"\" />");
		out.append("                                        </div>");
		out.append("                                    </div>");
		out.append("                                    <div class=\"col-md-6\">");
		out.append("                                        <div class=\"checkout-form-list\">");
		out.append("                                            <label>Họ <span class=\"required\">*</span></label>");
		out.append("                                            <input type=\"text\" placeholder=\"\" />");
		out.append("                                        </div>");
		out.append("                                    </div>");
		out.append("                                    <div class=\"col-md-12\">");
		out.append("                                        <div class=\"checkout-form-list\">");
		out.append("                                            <label>Tên Công ty</label>");
		out.append("                                            <input type=\"text\" placeholder=\"\" />");
		out.append("                                        </div>");
		out.append("                                    </div>");
		out.append("                                    <div class=\"col-md-12\">");
		out.append("                                        <div class=\"checkout-form-list\">");
		out.append("                                            <label>Địa chỉ <span class=\"required\">*</span></label>");
		out.append("                                            <input type=\"text\" placeholder=\"Địa chỉ chi tiết\" />");
		out.append("                                        </div>");
		out.append("                                    </div>");
		out.append("                                    <div class=\"col-md-12\">");
		out.append("                                        <div class=\"checkout-form-list\">");
		out.append("                                            <input type=\"text\" placeholder=\"Căn hộ, phòng, đơn vị...(không bắt buộc)\" />");
		out.append("                                        </div>");
		out.append("                                    </div>");
		out.append("                                    <div class=\"col-md-12\">");
		out.append("                                        <div class=\"checkout-form-list\">");
		out.append("                                            <label>Tỉnh/ Thành phố <span class=\"required\">*</span></label>");
		out.append("                                            <input type=\"text\" placeholder=\"Tỉnh/ Thành phố\" />");
		out.append("                                        </div>");
		out.append("                                    </div>");
		out.append("                                    <div class=\"col-md-6\">");
		out.append("                                        <div class=\"checkout-form-list\">");
		out.append("                                            <label>Quận/Huyện <span class=\"required\">*</span></label>");
		out.append("                                            <input type=\"text\" placeholder=\"\" />");
		out.append("                                        </div>");
		out.append("                                    </div>");
		out.append("                                    <div class=\"col-md-6\">");
		out.append("                                        <div class=\"checkout-form-list\">");
		out.append("                                            <label>Xã/Phường/Thị trấn <span class=\"required\">*</span></label>");
		out.append("                                            <input type=\"text\" placeholder=\"\" />");
		out.append("                                        </div>");
		out.append("                                    </div>");
		out.append("                                    <div class=\"col-md-6\">");
		out.append("                                        <div class=\"checkout-form-list\">");
		out.append("                                            <label>Mã bưu chính <span class=\"required\">*</span></label>");
		out.append("                                            <input type=\"text\" placeholder=\"Mã bưu chính\" />");
		out.append("                                        </div>");
		out.append("                                    </div>");
		out.append("                                    <div class=\"col-md-6\">");
		out.append("                                        <div class=\"checkout-form-list\">");
		out.append("                                            <label>Địa chỉ email <span class=\"required\">*</span></label>");
		out.append("                                            <input type=\"email\" placeholder=\"\" />");
		out.append("                                        </div>");
		out.append("                                    </div>");
		out.append("                                    <div class=\"col-md-6\">");
		out.append("                                        <div class=\"checkout-form-list\">");
		out.append("                                            <label>Số điện thoại <span class=\"required\">*</span></label>");
		out.append("                                            <input type=\"text\" placeholder=\"\" />");
		out.append("                                        </div>");
		out.append("                                    </div>");
		out.append("                                    <div class=\"col-md-12\">");
		out.append("                                        <div class=\"checkout-form-list create-acc\">");
		out.append("                                            <input id=\"cbox\" type=\"checkbox\" />");
		out.append("                                            <label>Đăng kí?</label>");
		out.append("                                        </div>");
		out.append("                                        <div id=\"cbox_info\" class=\"checkout-form-list create-account\">");
		out.append("                                            <p>Tạo tài khoản bằng cách điền thông tin bên dưới. Nếu bạn đã có tài khoản, vui lòng đăng nhập ở đầu trang.</p>");
		out.append("                                            <label>Mật khẩu<span class=\"required\">*</span></label>");
		out.append("                                            <input type=\"password\" placeholder=\"mật khẩu\" />");
		out.append("                                        </div>");
		out.append("                                    </div>");
		out.append("                                </div>");
		out.append("                                <div class=\"different-address\">");
		out.append("                                    <div class=\"ship-different-title\">");
		out.append("                                        <h3>");
		out.append("                                            <label>Bạn muốn nhận hàng ở địa chỉ khác?</label>");
		out.append("                                            <input id=\"ship-box\" type=\"checkbox\" />");
		out.append("                                        </h3>");
		out.append("                                    </div>");
		out.append("                                    <div id=\"ship-box-info\">");
		out.append("                                        <div class=\"row\">");
		out.append("                                            <div class=\"col-md-12\">");
		out.append("                                                <div class=\"country-select\">");
		out.append("                                                    <label>Quốc gia <span class=\"required\">*</span></label>");
		out.append("                                                    <select>");
		out.append("                                                        <option value=\"volvo\">Việt Nam</option>");
		out.append("                                                        <option value=\"saab\">Algeria</option>");
		out.append("                                                        <option value=\"mercedes\">Afghanistan</option>");
		out.append("                                                        <option value=\"audi\">Ghana</option>");
		out.append("                                                        <option value=\"audi2\">Albania</option>");
		out.append("                                                        <option value=\"audi3\">Bahrain</option>");
		out.append("                                                        <option value=\"audi4\">Colombia</option>");
		out.append("                                                        <option value=\"audi5\">Dominican Republic</option>");
		out.append("                                                    </select>");
		out.append("                                                </div>");
		out.append("                                            </div>");
		out.append("                                            <div class=\"col-md-6\">");
		out.append("                                                <div class=\"checkout-form-list\">");
		out.append("                                                    <label>Tên <span class=\"required\">*</span></label>");
		out.append("                                                    <input type=\"text\" placeholder=\"\" />");
		out.append("                                                </div>");
		out.append("                                            </div>");
		out.append("                                            <div class=\"col-md-6\">");
		out.append("                                                <div class=\"checkout-form-list\">");
		out.append("                                                    <label>Họ <span class=\"required\">*</span></label>");
		out.append("                                                    <input type=\"text\" placeholder=\"\" />");
		out.append("                                                </div>");
		out.append("                                            </div>");
		out.append("                                            <div class=\"col-md-12\">");
		out.append("                                                <div class=\"checkout-form-list\">");
		out.append("                                                    <label>Tên Công ty</label>");
		out.append("                                                    <input type=\"text\" placeholder=\"\" />");
		out.append("                                                </div>");
		out.append("                                            </div>");
		out.append("                                            <div class=\"col-md-12\">");
		out.append("                                                <div class=\"checkout-form-list\">");
		out.append("                                                    <label>Địa chỉ <span class=\"required\">*</span></label>");
		out.append("                                                    <input type=\"text\" placeholder=\"Địa chỉ chi tiết\" />");
		out.append("                                                </div>");
		out.append("                                            </div>");
		out.append("                                            <div class=\"col-md-12\">");
		out.append("                                                <div class=\"checkout-form-list\">");
		out.append("                                                    <input type=\"text\" placeholder=\"Căn hộ, phòng, đơn vị...(không bắt buộc)\" />");
		out.append("                                                </div>");
		out.append("                                            </div>");
		out.append("                                            <div class=\"col-md-12\">");
		out.append("                                                <div class=\"checkout-form-list\">");
		out.append("                                                    <label>Tỉnh/ Thành phố <span class=\"required\">*</span></label>");
		out.append("                                                    <input type=\"text\" placeholder=\"Tỉnh/ Thành phố\" />");
		out.append("                                                </div>");
		out.append("                                            </div>");
		out.append("                                            <div class=\"col-md-6\">");
		out.append("                                                <div class=\"checkout-form-list\">");
		out.append("                                                    <label>Quận/Huyện <span class=\"required\">*</span></label>");
		out.append("                                                    <input type=\"text\" placeholder=\"\" />");
		out.append("                                                </div>");
		out.append("                                            </div>");
		out.append("                                            <div class=\"col-md-6\">");
		out.append("                                                <div class=\"checkout-form-list\">");
		out.append("                                                    <label>Xã/Phường/Thị trấn <span class=\"required\">*</span></label>");
		out.append("                                                    <input type=\"text\" placeholder=\"\" />");
		out.append("                                                </div>");
		out.append("                                            </div>");
		out.append("                                            <div class=\"col-md-6\">");
		out.append("                                                <div class=\"checkout-form-list\">");
		out.append("                                                    <label>Mã bưu chính <span class=\"required\">*</span></label>");
		out.append("                                                    <input type=\"text\" placeholder=\"Mã bưu chính\" />");
		out.append("                                                </div>");
		out.append("                                            </div>");
		out.append("                                            <div class=\"col-md-6\">");
		out.append("                                                <div class=\"checkout-form-list\">");
		out.append("                                                    <label>Địa chỉ email <span class=\"required\">*</span></label>");
		out.append("                                                    <input type=\"email\" placeholder=\"\" />");
		out.append("                                                </div>");
		out.append("                                            </div>");
		out.append("                                            <div class=\"col-md-6\">");
		out.append("                                                <div class=\"checkout-form-list\">");
		out.append("                                                    <label>Số điện thoại <span class=\"required\">*</span></label>");
		out.append("                                                    <input type=\"text\" placeholder=\"\" />");
		out.append("                                                </div>");
		out.append("                                            </div>");
		out.append("                                            <div class=\"col-md-12\">");
		out.append("                                                <div class=\"checkout-form-list create-acc\">");
		out.append("                                                    <input id=\"cbox\" type=\"checkbox\" />");
		out.append("                                                    <label>Đăng kí?</label>");
		out.append("                                                </div>");
		out.append("                                                <div id=\"cbox_info\" class=\"checkout-form-list create-account\">");
		out.append("                                                    <p>Tạo tài khoản bằng cách điền thông tin bên dưới. Nếu bạn đã có tài khoản, vui lòng đăng nhập ở đầu trang.</p>");
		out.append("                                                    <label>Mật khẩu<span class=\"required\">*</span></label>");
		out.append("                                                    <input type=\"password\" placeholder=\"mật khẩu\" />");
		out.append("                                                </div>");
		out.append("                                            </div>");
		out.append("                                        </div>");
		out.append("                                    </div>");
		out.append("                                    <div class=\"order-notes\">");
		out.append("                                        <div class=\"checkout-form-list\">");
		out.append("                                            <label>Ghi chú đơn hàng</label>");
		out.append("                                            <textarea id=\"checkout-mess\" cols=\"30\" rows=\"10\" placeholder=\"gọi trước, giao hàng giờ hành chính...\"></textarea>");
		out.append("                                        </div>");
		out.append("                                    </div>");
		out.append("                                </div>");
		out.append("                            </div>");
		out.append("                        </div>");
		out.append("                        <div class=\"col-lg-6\">");
		out.append("                            <div class=\"your-order mb-30 \">");
		out.append("                                <h3>Đơn hàng của bạn</h3>");
		out.append("                                <div class=\"your-order-table table-responsive\">");
		out.append("                                    <table>");
		out.append("                                        <thead>");
		out.append("                                            <tr>");
		out.append("                                                <th class=\"product-name\">Sản phẩm</th>");
		out.append("                                                <th class=\"product-total\">Tổng</th>");
		out.append("                                            </tr>");
		out.append("                                        </thead>");
		out.append("                                        <tbody>");
		out.append("                                            <tr class=\"cart_item\">");
		out.append("                                                <td class=\"product-name\">");
		out.append("                                                    Vestibulum suscipit <strong class=\"product-quantity\"> × 1</strong>");
		out.append("                                                </td>");
		out.append("                                                <td class=\"product-total\">");
		out.append("                                                    <span class=\"amount\">$165.00</span>");
		out.append("                                                </td>");
		out.append("                                            </tr>");
		out.append("                                            <tr class=\"cart_item\">");
		out.append("                                                <td class=\"product-name\">");
		out.append("                                                    Vestibulum dictum magna <strong class=\"product-quantity\"> × 1</strong>");
		out.append("                                                </td>");
		out.append("                                                <td class=\"product-total\">");
		out.append("                                                    <span class=\"amount\">$50.00</span>");
		out.append("                                                </td>");
		out.append("                                            </tr>");
		out.append("                                        </tbody>");
		out.append("                                        <tfoot>");
		out.append("                                            <tr class=\"cart-subtotal\">");
		out.append("                                                <th>Tạm tính</th>");
		out.append("                                                <td><span class=\"amount\">$215.00</span></td>");
		out.append("                                            </tr>");
		out.append("                                            <tr class=\"shipping\">");
		out.append("                                                <th>Phí vận chuyển</th>");
		out.append("                                                <td>");
		out.append("                                                    <ul>");
		out.append("                                                        <li>");
		out.append("                                                            <input type=\"radio\" />");
		out.append("                                                            <label>");
		out.append("                                                                Phí cố định: <span class=\"amount\">$7.00</span>");
		out.append("                                                            </label>");
		out.append("                                                        </li>");
		out.append("                                                        <li>");
		out.append("                                                            <input type=\"radio\" />");
		out.append("                                                            <label>Miễn phí vận chuyển:</label>");
		out.append("                                                        </li>");
		out.append("                                                        <li></li>");
		out.append("                                                    </ul>");
		out.append("                                                </td>");
		out.append("                                            </tr>");
		out.append("                                            <tr class=\"order-total\">");
		out.append("                                                <th>Tổng đơn hàng</th>");
		out.append("                                                <td><strong><span class=\"amount\">$215.00</span></strong>");
		out.append("                                                </td>");
		out.append("                                            </tr>");
		out.append("                                        </tfoot>");
		out.append("                                    </table>");
		out.append("                                </div>");
		out.append("");
		out.append("                                <div class=\"payment-method\">");
		out.append("                                    <div class=\"accordion\" id=\"accordionExample\">");
		out.append("                                        <div class=\"card\">");
		out.append("                                            <div class=\"card-header\" id=\"headingOne\">");
		out.append("                                                <h5 class=\"mb-0\">");
		out.append("                                                    <button class=\"btn-link\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapseOne\"");
		out.append("                                                        aria-expanded=\"true\" aria-controls=\"collapseOne\">");
		out.append("                                                        Thanh toán bằng chuyển khoản");
		out.append("                                                    </button>");
		out.append("                                                </h5>");
		out.append("                                            </div>");
		out.append("");
		out.append("                                            <div id=\"collapseOne\" class=\"collapse show\" aria-labelledby=\"headingOne\"");
		out.append("                                                data-parent=\"#accordionExample\">");
		out.append("                                                <div class=\"card-body\">");
		out.append("                                                    Vui lòng chuyển khoản trực tiếp vào tài khoản của chúng tôi.");
		out.append("                                                    Hãy ghi mã đơn hàng làm nội dung chuyển khoản.");
		out.append("                                                    Đơn hàng sẽ chỉ được gửi đi sau khi chúng tôi nhận được thanh toán.");
		out.append("                                                </div>");
		out.append("                                            </div>");
		out.append("                                        </div>");
		out.append("                                        <div class=\"card\">");
		out.append("                                            <div class=\"card-header\" id=\"headingTwo\">");
		out.append("                                                <h5 class=\"mb-0\">");
		out.append("                                                    <button class=\"btn-link collapsed\" type=\"button\" data-toggle=\"collapse\"");
		out.append("                                                        data-target=\"#collapseTwo\" aria-expanded=\"false\" aria-controls=\"collapseTwo\">");
		out.append("                                                        Thanh toán bằng séc");
		out.append("                                                    </button>");
		out.append("                                                </h5>");
		out.append("                                            </div>");
		out.append("                                            <div id=\"collapseTwo\" class=\"collapse\" aria-labelledby=\"headingTwo\" data-parent=\"#accordionExample\">");
		out.append("                                                ");
		out.append("                                            </div>");
		out.append("                                        </div>");
		out.append("                                        <div class=\"card\">");
		out.append("                                            <div class=\"card-header\" id=\"headingThree\">");
		out.append("                                                <h5 class=\"mb-0\">");
		out.append("                                                    <button class=\"btn-link collapsed\" type=\"button\" data-toggle=\"collapse\"");
		out.append("                                                        data-target=\"#collapseThree\" aria-expanded=\"false\" aria-controls=\"collapseThree\">");
		out.append("                                                        PayPal");
		out.append("                                                    </button>");
		out.append("                                                </h5>");
		out.append("                                            </div>");
		out.append("                                            <div id=\"collapseThree\" class=\"collapse\" aria-labelledby=\"headingThree\" data-parent=\"#accordionExample\">");
		out.append("                                                <div class=\"card-body\">");
		out.append("                                                    Thanh toán qua PayPal – bạn có thể dùng thẻ tín dụng nếu không có tài khoản PayPal.");
		out.append("                                                </div>");
		out.append("                                            </div>");
		out.append("                                        </div>");
		out.append("                                    </div>");
		out.append("                                    <div class=\"order-button-payment mt-20\">");
		out.append("                                        <button type=\"submit\" class=\"btn theme-btn\">Đặt hàng</button>");
		out.append("                                    </div>");
		out.append("                                </div>");
		out.append("                            </div>");
		out.append("                        </div>");
		out.append("                    </div>");
		out.append("                </form>");
		out.append("            </div>");
		out.append("        </section>");
		out.append("        <!-- checkout-area end -->");
		out.append("");
		out.append("");
		out.append("</main>");

		RequestDispatcher footerDispatcher = request.getRequestDispatcher("/public/footer-view");
		footerDispatcher.include(request, response);
	}

	
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}
