package servlet.user.view;

import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;


@WebServlet("/public/blog")
public class UserBlogView extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    
    public UserBlogView() {
        super();
        // TODO Auto-generated constructor stub
    }

	
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

		response.setContentType("text/html;charset=UTF-8");
		request.setCharacterEncoding("UTF-8");

		PrintWriter out = response.getWriter();

		RequestDispatcher headerDispatcher = request.getRequestDispatcher("/public/header-view");
		headerDispatcher.include(request, response);

		out.append("	<main>");
		out.append("        <!-- breadcrumb-area-start -->");
		out.append("        <section class=\"breadcrumb-area\" data-background=\""+ request.getContextPath() +"/user/img/bg/page-title.png\">");
		out.append("            <div class=\"container\">");
		out.append("                <div class=\"row\">");
		out.append("                    <div class=\"col-xl-12\">");
		out.append("                        <div class=\"breadcrumb-text text-center\">");
		out.append("                            <h1>Tin Tức</h1>");
		out.append("                            <ul class=\"breadcrumb-menu\">");
		out.append("                                <li><a href=\""+ request.getContextPath() +"/public/home\">Trang Chủ</a></li>");
		out.append("                                <li><span>Tin Tức</span></li>");
		out.append("                            </ul>");
		out.append("                        </div>");
		out.append("                    </div>");
		out.append("                </div>");
		out.append("            </div>");
		out.append("        </section>");
		out.append("        <!-- breadcrumb-area-end -->");
		out.append("");
		out.append("        <!-- blog-area start -->");
		out.append("        <section class=\"blog-area pt-120 pb-80\">");
		out.append("            <div class=\"container\">");
		out.append("                <div class=\"row\">");
		out.append("                    <div class=\"col-lg-8\">");
		out.append("                        <article class=\"postbox post format-image mb-40\">");
		out.append("                            <div class=\"postbox__thumb\">");
		out.append("                                <a href=\"#\">");
		out.append("                                    <img src=\""+ request.getContextPath() +"/user/img/blog/b1.jpg\" alt=\"blog image\">");
		out.append("                                </a>");
		out.append("                            </div>");
		out.append("                            <div class=\"postbox__text p-50\">");
		out.append("                                <div class=\"post-meta mb-15\">");
		out.append("                                    <span><i class=\"far fa-calendar-check\"></i> Ngày 15 tháng 9, 2023 </span>");
		out.append("                                    <span><a href=\"#\"><i class=\"far fa-user\"></i> Bởi: Song Lê</a></span>");
		out.append("                                    <span><a href=\"#\"><i class=\"far fa-comments\"></i> 23 Bình luận</a></span>");
		out.append("                                </div>");
		out.append("                                <h3 class=\"blog-title\">");
		out.append("                                    <a href=\"#\">Xu Hướng Thiết Kế Nội Thất Tối Giản Lên Ngôi Năm Nay</a>");
		out.append("                                </h3>");
		out.append("                                <div class=\"post-text mb-20\">");
		out.append("                                    <p>Chủ nghĩa tối giản (Minimalism) không chỉ là một phong cách thiết kế, mà còn là một triết lý sống. Trong nội thất, nó tập trung vào việc loại bỏ những chi tiết thừa, giữ lại những gì thực sự cần thiết, tạo ra một không gian thoáng đãng, tinh tế và đầy cảm hứng.</p>");
		out.append("                                </div>");
		out.append("                                <div class=\"read-more mt-30\">");
		out.append("                                    <a href=\"#\" class=\"btn theme-btn\">Đọc thêm</a>");
		out.append("                                </div>");
		out.append("                            </div>");
		out.append("                        </article>");
		out.append("                        <article class=\"postbox post format-video mb-40\">");
		out.append("                            <div class=\"postbox__video\">");
		out.append("                                <img src=\""+ request.getContextPath() +"/user/img/blog/b6.jpg\" alt=\"blog image\">");
		out.append("                                <a class=\"popup-video video-btn\" href=\"https://www.youtube.com/watch?v=Y6MlVop80y0\"><i class=\"fas fa-play\"></i></a>");
		out.append("                            </div>");
		out.append("                            <div class=\"postbox__text p-50\">");
		out.append("                                <div class=\"post-meta mb-15\">");
		out.append("                                    <span><i class=\"far fa-calendar-check\"></i> Ngày 10 tháng 9, 2023 </span>");
		out.append("                                    <span><a href=\"#\"><i class=\"far fa-user\"></i> Bởi: Song Lê</a></span>");
		out.append("                                    <span><a href=\"#\"><i class=\"far fa-comments\"></i> 18 Bình luận</a></span>");
		out.append("                                </div>");
		out.append("                                <h3 class=\"blog-title\">");
		out.append("                                    <a href=\"#\">Bí Quyết Chọn Sofa Hoàn Hảo Cho Phòng Khách Hiện Đại</a>");
		out.append("                                </h3>");
		out.append("                                <div class=\"post-text mb-20\">");
		out.append("                                    <p>Sofa là trái tim của phòng khách, nơi cả gia đình quây quần và tiếp đón bạn bè. Việc lựa chọn một bộ sofa phù hợp không chỉ về kích thước, kiểu dáng mà còn về chất liệu và màu sắc sẽ quyết định đến toàn bộ thẩm mỹ của không gian.</p>");
		out.append("                                </div>");
		out.append("                                <div class=\"read-more mt-30\">");
		out.append("                                    <a href=\"#\" class=\"btn theme-btn\">Đọc thêm</a>");
		out.append("                                </div>");
		out.append("                            </div>");
		out.append("                        </article>");
		out.append("                        <article class=\"postbox post format-gallery mb-40\">");
		out.append("                            <div class=\"postbox__gallery\">");
		out.append("                                <img src=\""+ request.getContextPath() +"/user/img/blog/b5.jpg\" alt=\"blog image\">");
		out.append("                                <img src=\""+ request.getContextPath() +"/user/img/blog/b6.jpg\" alt=\"blog image\">");
		out.append("                                <img src=\""+ request.getContextPath() +"/user/img/blog/b7.jpg\" alt=\"blog image\">");
		out.append("                            </div>");
		out.append("                            <div class=\"postbox__text p-50\">");
		out.append("                                <div class=\"post-meta mb-15\">");
		out.append("                                    <span><i class=\"far fa-calendar-check\"></i> Ngày 5 tháng 9, 2023 </span>");
		out.append("                                    <span><a href=\"#\"><i class=\"far fa-user\"></i> Bởi: Song Lê</a></span>");
		out.append("                                    <span><a href=\"#\"><i class=\"far fa-comments\"></i> 31 Bình luận</a></span>");
		out.append("                                </div>");
		out.append("                                <h3 class=\"blog-title\">");
		out.append("                                    <a href=\"#\">Mang Thiên Nhiên Vào Nhà Với Vật Liệu Gỗ Tự Nhiên</a>");
		out.append("                                </h3>");
		out.append("                                <div class=\"post-text mb-20\">");
		out.append("                                    <p>Gỗ tự nhiên luôn là lựa chọn hàng đầu trong thiết kế nội thất cao cấp nhờ vẻ đẹp mộc mạc, ấm cúng và độ bền vượt thời gian. Từ gỗ sồi, gỗ óc chó đến gỗ teak, mỗi loại gỗ đều mang một câu chuyện và một vẻ đẹp riêng, góp phần tạo nên một không gian sống gần gũi với thiên nhiên.</p>");
		out.append("                                </div>");
		out.append("                                <div class=\"read-more mt-30\">");
		out.append("                                    <a href=\"#\" class=\"btn theme-btn\">Đọc thêm</a>");
		out.append("                                </div>");
		out.append("                            </div>");
		out.append("                        </article>");
		out.append("                        <article class=\"postbox post format-audio mb-40\">");
		out.append("                            <div class=\"postbox__audio embed-responsive embed-responsive-16by9\">");
		out.append("                                <iframe src=\"https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/469608615&amp;color=%23ff0000&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;show_teaser=true&amp;visual=true\"></iframe>");
		out.append("                            </div>");
		out.append("                            <div class=\"postbox__text p-50\">");
		out.append("                                <div class=\"post-meta mb-15\">");
		out.append("                                    <span><i class=\"far fa-calendar-check\"></i> Ngày 1 tháng 9, 2023 </span>");
		out.append("                                    <span><a href=\"#\"><i class=\"far fa-user\"></i> Bởi: Song Lê</a></span>");
		out.append("                                    <span><a href=\"#\"><i class=\"far fa-comments\"></i> 12 Bình luận</a></span>");
		out.append("                                </div>");
		out.append("                                <h3 class=\"blog-title\">");
		out.append("                                    <a href=\"#\">Podcast: Nghệ Thuật Bài Trí Ánh Sáng Trong Không Gian Sống</a>");
		out.append("                                </h3>");
		out.append("                                <div class=\"post-text mb-20\">");
		out.append("                                    <p>Ánh sáng là yếu tố quan trọng quyết định cảm xúc và không khí của một căn phòng. Trong số podcast này, chúng ta sẽ cùng chuyên gia của Song Lê khám phá cách kết hợp ánh sáng tự nhiên và nhân tạo để tạo ra những hiệu ứng thị giác ấn tượng, làm nổi bật vẻ đẹp của đồ nội thất.</p>");
		out.append("                                </div>");
		out.append("                                <div class=\"read-more mt-30\">");
		out.append("                                    <a href=\"#\" class=\"btn theme-btn\">Đọc thêm</a>");
		out.append("                                </div>");
		out.append("                            </div>");
		out.append("                        </article>");
		out.append("                        <article class=\"postbox post format-quote mb-40\">");
		out.append("                            <div class=\"post-text\">");
		out.append("                                <blockquote>");
		out.append("                                    <p>Ngôi nhà là nơi trái tim thuộc về, và nội thất là ngôn ngữ kể nên câu chuyện của trái tim đó.</p>");
		out.append("                                    <footer>- Song Lê</footer>");
		out.append("                                </blockquote>");
		out.append("                            </div>");
		out.append("                        </article>");
		out.append("                        <div class=\"basic-pagination basic-pagination-2 mb-40\">");
		out.append("                            <ul>");
		out.append("                                <li><a href=\"#\"><i class=\"fas fa-angle-double-left\"></i></a></li>");
		out.append("                                <li class=\"active\"><a href=\"#\">1</a></li>");
		out.append("                                <li><a href=\"#\">2</a></li>");
		out.append("                                <li><a href=\"#\">3</a></li>");
		out.append("                                <li><a href=\"#\"><i class=\"fas fa-ellipsis-h\"></i></a></li>");
		out.append("                                <li><a href=\"#\"><i class=\"fas fa-angle-double-right\"></i></a></li>");
		out.append("                            </ul>");
		out.append("                        </div>");
		out.append("                    </div>");
		out.append("                    <div class=\"col-lg-4\">");
		out.append("                        <div class=\"widget mb-40\">");
		out.append("                            <div class=\"widget-title-box mb-30\">");
		out.append("                                <span class=\"animate-border\"></span>");
		out.append("                                <h3 class=\"widget-title\">Tìm Kiếm</h3>");
		out.append("                            </div>");
		out.append("                            <form class=\"search-form\">");
		out.append("                                <input type=\"text\" placeholder=\"Nhập từ khóa...\">");
		out.append("                                <button type=\"submit\"><i class=\"fas fa-search\"></i></button>");
		out.append("                            </form>");
		out.append("                        </div>");
		out.append("                        <div class=\"widget mb-40\">");
		out.append("                            <div class=\"widget-title-box mb-30\">");
		out.append("                                <span class=\"animate-border\"></span>");
		out.append("                                <h3 class=\"widget-title\">Về Chúng Tôi</h3>");
		out.append("                            </div>");
		out.append("                            <div class=\"about-me text-center\">");
		out.append("                                <img src=\""+ request.getContextPath() +"/user/img/logo/logo.png\" alt=\"\">");
		out.append("                                <h4>Nội Thất Song Lê</h4>");
		out.append("                                <p>Kiến tạo không gian sống đẳng cấp, nơi mỗi món đồ nội thất là một tác phẩm nghệ thuật.</p>");
		out.append("                                <div class=\"widget-social-icon\">");
		out.append("                                    <a href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>");
		out.append("                                    <a href=\"#\"><i class=\"fab fa-twitter\"></i></a>");
		out.append("                                    <a href=\"#\"><i class=\"fab fa-behance\"></i></a>");
		out.append("                                    <a href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a>");
		out.append("                                    <a href=\"#\"><i class=\"fab fa-youtube\"></i></a>");
		out.append("                                </div>");
		out.append("                            </div>");
		out.append("                        </div>");
		out.append("                        <div class=\"widget mb-40\">");
		out.append("                            <div class=\"widget-title-box mb-30\">");
		out.append("                                <span class=\"animate-border\"></span>");
		out.append("                                <h3 class=\"widget-title\">Bài Viết Nổi Bật</h3>");
		out.append("                            </div>");
		out.append("                            <ul class=\"recent-posts\">");
		out.append("                                <li>");
		out.append("                                    <div class=\"widget-posts-image\">");
		out.append("                                        <a href=\"#\"><img src=\""+ request.getContextPath() +"/user/img/blog/details/img1.jpg\" alt=\"\"></a>");
		out.append("                                    </div>");
		out.append("                                    <div class=\"widget-posts-body\">");
		out.append("                                        <h6 class=\"widget-posts-title\"><a href=\"#\">5 Mẹo nhỏ giúp phòng khách rộng hơn</a></h6>");
		out.append("                                        <div class=\"widget-posts-meta\">Ngày 18 tháng 10, 2023 </div>");
		out.append("                                    </div>");
		out.append("                                </li>");
		out.append("                                <li>");
		out.append("                                    <div class=\"widget-posts-image\">");
		out.append("                                        <a href=\"#\"><img src=\""+ request.getContextPath() +"/user/img/blog/details/img2.jpg\" alt=\"\"></a>");
		out.append("                                    </div>");
		out.append("                                    <div class=\"widget-posts-body\">");
		out.append("                                        <h6 class=\"widget-posts-title\"><a href=\"#\">Chọn bàn ăn cho gia đình nhiều thế hệ</a></h6>");
		out.append("                                        <div class=\"widget-posts-meta\">Ngày 24 tháng 10, 2023 </div>");
		out.append("                                    </div>");
		out.append("                                </li>");
		out.append("                                <li>");
		out.append("                                    <div class=\"widget-posts-image\">");
		out.append("                                        <a href=\"#\"><img src=\""+ request.getContextPath() +"/user/img/blog/details/img3.jpg\" alt=\"\"></a>");
		out.append("                                    </div>");
		out.append("                                    <div class=\"widget-posts-body\">");
		out.append("                                        <h6 class=\"widget-posts-title\"><a href=\"#\">Tủ quần áo thông minh: Giải pháp cho nhà nhỏ</a></h6>");
		out.append("                                        <div class=\"widget-posts-meta\">Ngày 28 tháng 10, 2023 </div>");
		out.append("                                    </div>");
		out.append("                                </li>");
		out.append("                            </ul>");
		out.append("                        </div>");
		out.append("                        <div class=\"widget mb-40\">");
		out.append("                            <div class=\"widget-title-box mb-30\">");
		out.append("                                <span class=\"animate-border\"></span>");
		out.append("                                <h3 class=\"widget-title\">Chuyên Mục</h3>");
		out.append("                            </div>");
		out.append("                            <ul class=\"cat\">");
		out.append("                                <li>");
		out.append("                                    <a href=\"#\">Phong Cách Sống <span class=\"f-right\">78</span></a>");
		out.append("                                </li>");
		out.append("                                <li>");
		out.append("                                    <a href=\"#\">Cảm Hứng <span class=\"f-right\">42</span></a>");
		out.append("                                </li>");
		out.append("                                <li>");
		out.append("                                    <a href=\"#\">Xu Hướng <span class=\"f-right\">32</span></a>");
		out.append("                                </li>");
		out.append("                                <li>");
		out.append("                                    <a href=\"#\">Mẹo Hay <span class=\"f-right\">85</span></a>");
		out.append("                                </li>");
		out.append("                                <li>");
		out.append("                                    <a href=\"#\">Thương Hiệu <span class=\"f-right\">05</span></a>");
		out.append("                                </li>");
		out.append("                            </ul>");
		out.append("                        </div>");
		out.append("                        <div class=\"widget mb-40\">");
		out.append("                            <div class=\"widget-title-box mb-30\">");
		out.append("                                <span class=\"animate-border\"></span>");
		out.append("                                <h3 class=\"widget-title\">Mạng Xã Hội</h3>");
		out.append("                            </div>");
		out.append("                            <div class=\"social-profile\">");
		out.append("                                <a href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>");
		out.append("                                <a href=\"#\"><i class=\"fab fa-twitter\"></i></a>");
		out.append("                                <a href=\"#\"><i class=\"fab fa-behance\"></i></a>");
		out.append("                                <a href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a>");
		out.append("                                <a href=\"#\"><i class=\"fab fa-youtube\"></i></a>");
		out.append("                            </div>");
		out.append("                        </div>");
		out.append("                        <div class=\"widget mb-40\">");
		out.append("                            <div class=\"widget-title-box mb-30\">");
		out.append("                                <span class=\"animate-border\"></span>");
		out.append("                                <h3 class=\"widget-title\">Hình Ảnh Instagram</h3>");
		out.append("                            </div>");
		out.append("                            <ul id=\"Instafeed\"></ul>");
		out.append("                        </div>");
		out.append("                        <div class=\"widget mb-40\">");
		out.append("                            <div class=\"widget-title-box mb-30\">");
		out.append("                                <span class=\"animate-border\"></span>");
		out.append("                                <h3 class=\"widget-title\">Thẻ</h3>");
		out.append("                            </div>");
		out.append("                            <div class=\"tag\">");
		out.append("                                <a href=\"#\">Nổi bật</a>");
		out.append("                                <a href=\"#\">Thiết kế</a>");
		out.append("                                <a href=\"#\">Tiện ích</a>");
		out.append("                                <a href=\"#\">Phát triển</a>");
		out.append("                                <a href=\"#\">Tư vấn</a>");
		out.append("                                <a href=\"#\">Sofa</a>");
		out.append("                                <a href=\"#\">Bàn ăn</a>");
		out.append("                                <a href=\"#\">UX</a>");
		out.append("                                <a href=\"#\">Kinh doanh</a>");
		out.append("                                <a href=\"#\">Nội thất</a>");
		out.append("                                <a href=\"#\">Giường ngủ</a>");
		out.append("                                <a href=\"#\">Công nghệ</a>");
		out.append("                            </div>");
		out.append("                        </div>");
		out.append("                        <div class=\"widget mb-40 p-0 b-0\">");
		out.append("                            <div class=\"banner-widget\">");
		out.append("                                <a href=\"#\"><img src=\""+ request.getContextPath() +"/user/img/blog/details/banner.jpg\" alt=\"\"></a>");
		out.append("                            </div>");
		out.append("                        </div>");
		out.append("                    </div>");
		out.append("                </div>");
		out.append("            </div>");
		out.append("        </section>");
		out.append("        <!-- blog-area end -->");
		out.append("    </main>");

		RequestDispatcher footerDispatcher = request.getRequestDispatcher("/public/footer-view");
		footerDispatcher.include(request, response);

	}

	
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}
