package servlet.admin.view;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;


@WebServlet("/admin/orders-view")
public class OrdersView extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    
    public OrdersView() {
        super();
        // TODO Auto-generated constructor stub
    }

	
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		response.setContentType("text/html; charset=UTF-8");
		response.setCharacterEncoding("UTF-8");		 
		
		PrintWriter out = response.getWriter();
		request.setAttribute("view", "order");
		RequestDispatcher headerDispatcher = request.getRequestDispatcher("/admin/header-view");
	    headerDispatcher.include(request, response);


		out.append("\"<main id=\"main\" class=\"main\">");
		out.append("");
		out.append("    <div class=\"pagetitle\">");
		out.append("      <nav>");
		out.append("        <ol class=\"breadcrumb\">");
		out.append("          <li class=\"breadcrumb-item fs-6\"><a href=\"index.html\">Trang chủ</a></li>");
		out.append("          <li class=\"breadcrumb-item fs-6\">Đơn hàng</li>");
		out.append("        </ol>");
		out.append("      </nav>");
		out.append("    </div><!-- End Page Title -->");
		out.append("");
		out.append("    <section class=\"section\">");
		out.append("      <div class=\"row\">");
		out.append("        <div class=\"col-lg-12\">");
		out.append("");
		out.append("          <div class=\"card mb-3\">");
		out.append("            <div class=\"card-body\">");
		out.append("              <div class=\"d-flex align-items-center mt-2 mb-3 filter-label\">");
		out.append("                <i class=\"bi bi-funnel-fill me-2\"></i>");
		out.append("                <span>BỘ LỌC</span>");
		out.append("              </div>");
		out.append("");
		out.append("              <form id=\"orderFilterForm\" class=\"container\">");
		out.append("                <div class=\"row g-3 align-items-end\">");
		out.append("                  <!-- Khoảng giá -->");
		out.append("                  <div class=\"col-md-2\">");
		out.append("                    <label for=\"priceRange\" class=\"form-label\">Khoảng giá</label>");
		out.append("                    <select class=\"form-select\" id=\"priceRange\">");
		out.append("                      <option value=\"\">Tất cả</option>");
		out.append("                      <option value=\"low\">Dưới 500k</option>");
		out.append("                      <option value=\"mid\">500k - 1 triệu</option>");
		out.append("                      <option value=\"high\">Trên 1 triệu</option>");
		out.append("                    </select>");
		out.append("                  </div>");
		out.append("");
		out.append("                  <!-- Trạng thái -->");
		out.append("                  <div class=\"col-md-2\">");
		out.append("                    <label for=\"orderStatus\" class=\"form-label\">Trạng thái</label>");
		out.append("                    <select class=\"form-select\" id=\"orderStatus\">");
		out.append("                      <option value=\"\">Tất cả</option>");
		out.append("                      <option value=\"pending\">Chờ xác nhận</option>");
		out.append("                      <option value=\"shipping\">Đang giao</option>");
		out.append("                      <option value=\"shipped\">Đã giao</option>");
		out.append("                      <option value=\"cancelled\">Đã hủy</option>");
		out.append("                    </select>");
		out.append("                  </div>");
		out.append("");
		out.append("                  <!-- Phương thức thanh toán -->");
		out.append("                  <div class=\"col-md-2\">");
		out.append("                    <label for=\"paymentMethod\" class=\"form-label\">Thanh toán</label>");
		out.append("                    <select class=\"form-select\" id=\"paymentMethod\">");
		out.append("                      <option value=\"\">Tất cả</option>");
		out.append("                      <option value=\"cod\">COD</option>");
		out.append("                      <option value=\"bank\">Chuyển khoản</option>");
		out.append("                    </select>");
		out.append("                  </div>");
		out.append("");
		out.append("                  <!-- Sắp xếp -->");
		out.append("                  <div class=\"col-md-2\">");
		out.append("                    <label for=\"orderSort\" class=\"form-label\">Đơn đặt hàng</label>");
		out.append("                    <select class=\"form-select\" id=\"orderSort\">");
		out.append("                      <option value=\"\">Tất cả</option>");
		out.append("                      <option value=\"newest\">Mới Nhất</option>");
		out.append("                      <option value=\"oldest\">Cũ nhất</option>");
		out.append("                    </select>");
		out.append("                  </div>");
		out.append("");
		out.append("                  <!-- Nút lọc -->");
		out.append("                  <div class=\"col-md-1\">");
		out.append("                    <button type=\"button\" class=\"btn btn-primary mt-3 w-100\" onclick=\"applyOrderFilter()\">Lọc</button>");
		out.append("                  </div>");
		out.append("");
		out.append("                </div>");
		out.append("              </form>");
		out.append("");
		out.append("              <!-- Tổng quan số lượng đơn hàng -->");
		out.append("              <div class=\"my-4\">");
		out.append("                <h5 class=\"my-3 fw-bold\">Tổng quan đơn hàng</h5>");
		out.append("                <div class=\"row text-center g-4\">");
		out.append("                  <div class=\"col-md-3 col-6\">");
		out.append("                    <div class=\"border rounded p-3 bg-light\">");
		out.append("                      <h6 class=\"fs-5 fw-bold mt-2\">Tổng đơn hàng</h6>");
		out.append("                      <p class=\"fs-4 fw-bold\">18</p>");
		out.append("                    </div>");
		out.append("                  </div>");
		out.append("                  <div class=\"col-md-3 col-6\">");
		out.append("                    <div class=\"border rounded p-3 bg-warning bg-opacity-25\">");
		out.append("                      <h6 class=\"fs-5 fw-bold mt-2\">Đang xử lý</h6>");
		out.append("                      <p class=\"fs-4 fw-bold text-warning\" id=\"processing-orders\">8</p>");
		out.append("                    </div>");
		out.append("                  </div>");
		out.append("                  <div class=\"col-md-3 col-6\">");
		out.append("                    <div class=\"border rounded p-3 bg-success bg-opacity-25\">");
		out.append("                      <h6 class=\"fs-5 fw-bold mt-2\">Thành công</h6>");
		out.append("                      <p class=\"fs-4 fw-bold text-success\" id=\"successful-orders\">5</p>");
		out.append("                    </div>");
		out.append("                  </div>");
		out.append("                  <div class=\"col-md-3 col-6\">");
		out.append("                    <div class=\"border rounded p-3 bg-danger bg-opacity-25\">");
		out.append("                      <h6 class=\"fs-5 fw-bold mt-2\">Đã huỷ</h6>");
		out.append("                      <p class=\"fs-4 fw-bold text-danger\" id=\"cancelled-orders\">5</p>");
		out.append("                    </div>");
		out.append("                  </div>");
		out.append("                </div>");
		out.append("              </div>");
		out.append("            </div>");
		out.append("");
		out.append("          </div>");
		out.append("");
		out.append("          <div class=\"card\">");
		out.append("            <div class=\"card-body\">");
		out.append("");
		out.append("              <div class=\"table-responsive\">");
		out.append("");
		out.append("                <!-- Table with stripped rows -->");
		out.append("                <table class=\"table table-striped datatable table-hover\">");
		out.append("                  <thead>");
		out.append("                    <tr>");
		out.append("                      <th>");
		out.append("                        Mã đơn hàng");
		out.append("                      </th>");
		out.append("                      <th>Khách hàng</th>");
		out.append("                      <th data-type=\"date\" data-format=\"YYYY/DD/MM\">Thời gian</th>");
		out.append("                      <th>Tổng tiền</th>");
		out.append("                      <th>Trạng thái</th>");
		out.append("                      <th>Chức năng</th>");
		out.append("                    </tr>");
		out.append("                  </thead>");
		out.append("                  <tbody>");
		out.append("");
		out.append("                    <tr>");
		out.append("                      <td class=\"align-middle\">AC#1007</td>");
		out.append("                      <td class=\"align-middle\">Lê Văn Chuyền</td>");
		out.append("                      <td class=\"align-middle\">16/3/2025</td>");
		out.append("                      <td class=\"align-middle\">350000đ</td>");
		out.append("                      <td class=\"align-middle\">");
		out.append("                        <span class=\"badge bg-warning text-dark p-2\">Đang giao</span>");
		out.append("                      </td>");
		out.append("                      <td class=\"align-middle\">");
		out.append("                        <a href=\"../admin/single-order-view\"><i class=\"bi bi-eye fs-6 text-secondary ms-2 pointer\"></i></a>");
		out.append("                        <i class=\"deleteIcon bi bi-trash fs-6 text-danger ms-2 pointer\"></i>");
		out.append("                      </td>");
		out.append("                    </tr>");
		out.append("");
		out.append("                    <tr>");
		out.append("                      <td class=\"align-middle\">BC#1007</td>");
		out.append("                      <td class=\"align-middle\">Đặng Ánh Nhật</td>");
		out.append("                      <td class=\"align-middle\">16/3/2025</td>");
		out.append("                      <td class=\"align-middle\">350000đ</td>");
		out.append("                      <td class=\"align-middle\">");
		out.append("                        <a href=\"../admin/single-order-process-view\" class=\"btn badge bg-secondary p-2\">Chờ xác nhận</a>");
		out.append("                      </td>");
		out.append("                      <td class=\"align-middle\">");
		out.append("                        <a href=\"../admin/single-order-view\"><i class=\"bi bi-eye fs-6 text-secondary ms-2 pointer\"></i></a>");
		out.append("                        <i class=\"deleteIcon bi bi-trash fs-6 text-danger ms-2 pointer\"></i>");
		out.append("                      </td>");
		out.append("                    </tr>");
		out.append("");
		out.append("                    <tr>");
		out.append("                      <td class=\"align-middle\">DC#1007</td>");
		out.append("                      <td class=\"align-middle\">Đặng Ánh Nhật</td>");
		out.append("                      <td class=\"align-middle\">16/3/2025</td>");
		out.append("                      <td class=\"align-middle\">350000đ</td>");
		out.append("                      <td class=\"align-middle\">");
		out.append("                        <span class=\"badge bg-warning text-dark p-2\">Đang giao</span>");
		out.append("                      </td>");
		out.append("                      <td class=\"align-middle\">");
		out.append("                        <a href=\"../admin/single-order-view\"><i class=\"bi bi-eye fs-6 text-secondary ms-2 pointer\"></i></a>");
		out.append("");
		out.append("                        <i class=\"deleteIcon bi bi-trash fs-6 text-danger ms-2 pointer\"></i>");
		out.append("                      </td>");
		out.append("                    </tr>");
		out.append("");
		out.append("                    <tr>");
		out.append("                      <td class=\"align-middle\">EC#1007</td>");
		out.append("                      <td class=\"align-middle\">Đặng Ánh Nhật</td>");
		out.append("                      <td class=\"align-middle\">16/3/2025</td>");
		out.append("                      <td class=\"align-middle\">350000đ</td>");
		out.append("                      <td class=\"align-middle\">");
		out.append("                        <span class=\"badge bg-success p-2\">Thành công</span>");
		out.append("                      </td>");
		out.append("                      <td class=\"align-middle\">");
		out.append("                        <a href=\"../admin/single-order-view\"><i class=\"bi bi-eye fs-6 text-secondary ms-2 pointer\"></i></a>");
		out.append("");
		out.append("                        <i class=\"deleteIcon bi bi-trash fs-6 text-danger ms-2 pointer\"></i>");
		out.append("                      </td>");
		out.append("                    </tr>");
		out.append("");
		out.append("");
		out.append("                    <tr>");
		out.append("                      <td class=\"align-middle\">FC#1007</td>");
		out.append("                      <td class=\"align-middle\">Đặng Ánh Nhật</td>");
		out.append("                      <td class=\"align-middle\">16/3/2025</td>");
		out.append("                      <td class=\"align-middle\">350000đ</td>");
		out.append("                      <td class=\"align-middle\">");
		out.append("                        <a href=\"../admin/single-order-process-view\" class=\"btn badge bg-secondary p-2\">Chờ xác nhận</a>");
		out.append("                      </td>");
		out.append("                      <td class=\"align-middle\">");
		out.append("                        <a href=\"../admin/single-order-view\"><i class=\"bi bi-eye fs-6 text-secondary ms-2 pointer\"></i></a>");
		out.append("");
		out.append("                        <i class=\"deleteIcon bi bi-trash fs-6 text-danger ms-2 pointer\"></i>");
		out.append("                      </td>");
		out.append("                    </tr>");
		out.append("                    <tr>");
		out.append("                      <td class=\"align-middle\">BC#1007</td>");
		out.append("                      <td class=\"align-middle\">Đặng Ánh Nhật</td>");
		out.append("                      <td class=\"align-middle\">16/3/2025</td>");
		out.append("                      <td class=\"align-middle\">350000đ</td>");
		out.append("                      <td class=\"align-middle\">");
		out.append("                        <span class=\"badge bg-success p-2\">Thành công</span>");
		out.append("                      </td>");
		out.append("                      <td class=\"align-middle\">");
		out.append("                        <a href=\"../admin/single-order-view\"><i class=\"bi bi-eye fs-6 text-secondary ms-2 pointer\"></i></a>");
		out.append("");
		out.append("                        <i class=\"deleteIcon bi bi-trash fs-6 text-danger ms-2 pointer\"></i>");
		out.append("                      </td>");
		out.append("                    </tr>");
		out.append("");
		out.append("                    <tr>");
		out.append("                      <td class=\"align-middle\">DC#1007</td>");
		out.append("                      <td class=\"align-middle\">Đặng Ánh Nhật</td>");
		out.append("                      <td class=\"align-middle\">16/3/2025</td>");
		out.append("                      <td class=\"align-middle\">350000đ</td>");
		out.append("                      <td class=\"align-middle\">");
		out.append("                        <span class=\"badge bg-danger p-2\">Đã huỷ</span>");
		out.append("                      </td>");
		out.append("                      <td class=\"align-middle\">");
		out.append("                        <a href=\"../admin/single-order-view\"><i class=\"bi bi-eye fs-6 text-secondary ms-2 pointer\"></i></a>");
		out.append("");
		out.append("                        <i class=\"deleteIcon bi bi-trash fs-6 text-danger ms-2 pointer\"></i>");
		out.append("                      </td>");
		out.append("                    </tr>");
		out.append("");
		out.append("                    <tr>");
		out.append("                      <td class=\"align-middle\">EC#1007</td>");
		out.append("                      <td class=\"align-middle\">Đặng Ánh Nhật</td>");
		out.append("                      <td class=\"align-middle\">16/3/2025</td>");
		out.append("                      <td class=\"align-middle\">350000đ</td>");
		out.append("                      <td class=\"align-middle\">");
		out.append("                        <span class=\"badge bg-danger p-2\">Đã huỷ</span>");
		out.append("                      </td>");
		out.append("                      <td class=\"align-middle\">");
		out.append("                        <a href=\"../admin/single-order-view\"><i class=\"bi bi-eye fs-6 text-secondary ms-2 pointer\"></i></a>");
		out.append("");
		out.append("                        <i class=\"deleteIcon bi bi-trash fs-6 text-danger ms-2 pointer\"></i>");
		out.append("                      </td>");
		out.append("                    </tr>");
		out.append("");
		out.append("");
		out.append("                    <tr>");
		out.append("                      <td class=\"align-middle\">FC#1007</td>");
		out.append("                      <td class=\"align-middle\">Đặng Ánh Nhật</td>");
		out.append("                      <td class=\"align-middle\">16/3/2025</td>");
		out.append("                      <td class=\"align-middle\">350000đ</td>");
		out.append("                      <td class=\"align-middle\">");
		out.append("                        <span class=\"badge bg-warning text-dark p-2\">Đang giao</span>");
		out.append("                      </td>");
		out.append("                      <td class=\"align-middle\">");
		out.append("                        <a href=\"../admin/single-order-view\"><i class=\"bi bi-eye fs-6 text-secondary ms-2 pointer\"></i></a>");
		out.append("");
		out.append("                        <i class=\"deleteIcon bi bi-trash fs-6 text-danger ms-2 pointer\"></i>");
		out.append("                      </td>");
		out.append("                    </tr>");
		out.append("");
		out.append("                    <tr>");
		out.append("                      <td class=\"align-middle\">HC#1007</td>");
		out.append("                      <td class=\"align-middle\">Đặng Ánh Nhật</td>");
		out.append("                      <td class=\"align-middle\">16/3/2025</td>");
		out.append("                      <td class=\"align-middle\">350000đ</td>");
		out.append("                      <td class=\"align-middle\">");
		out.append("                        <span class=\"badge bg-danger p-2\">Đã huỷ</span>");
		out.append("                      </td>");
		out.append("                      <td class=\"align-middle\">");
		out.append("                        <a href=\"../admin/single-order-view\"><i class=\"bi bi-eye fs-6 text-secondary ms-2 pointer\"></i></a>");
		out.append("");
		out.append("                        <i class=\"deleteIcon bi bi-trash fs-6 text-danger ms-2 pointer\"></i>");
		out.append("                      </td>");
		out.append("                    </tr>");
		out.append("");
		out.append("                    <tr>");
		out.append("                      <td class=\"align-middle\">KC#1007</td>");
		out.append("                      <td class=\"align-middle\">Đặng Ánh Nhật</td>");
		out.append("                      <td class=\"align-middle\">16/3/2025</td>");
		out.append("                      <td class=\"align-middle\">350000đ</td>");
		out.append("                      <td class=\"align-middle\">");
		out.append("                        <span class=\"badge bg-warning text-dark p-2\">Đang giao</span>");
		out.append("                      </td>");
		out.append("                      <td class=\"align-middle\">");
		out.append("                        <a href=\"../admin/single-order-view\"><i class=\"bi bi-eye fs-6 text-secondary ms-2 pointer\"></i></a>");
		out.append("");
		out.append("                        <i class=\"deleteIcon bi bi-trash fs-6 text-danger ms-2 pointer\"></i>");
		out.append("                      </td>");
		out.append("                    </tr>");
		out.append("");
		out.append("                    <tr>");
		out.append("                      <td class=\"align-middle\">GC#1007</td>");
		out.append("                      <td class=\"align-middle\">Đặng Ánh Nhật</td>");
		out.append("                      <td class=\"align-middle\">16/3/2025</td>");
		out.append("                      <td class=\"align-middle\">350000đ</td>");
		out.append("                      <td class=\"align-middle\">");
		out.append("                        <span class=\"badge bg-warning text-dark p-2\">Đang giao</span>");
		out.append("                      </td>");
		out.append("                      <td class=\"align-middle\">");
		out.append("                        <a href=\"../admin/single-order-view\"><i class=\"bi bi-eye fs-6 text-secondary ms-2 pointer\"></i></a>");
		out.append("");
		out.append("                        <i class=\"deleteIcon bi bi-trash fs-6 text-danger ms-2 pointer\"></i>");
		out.append("                      </td>");
		out.append("                    </tr>");
		out.append("");
		out.append("                    <tr>");
		out.append("                      <td class=\"align-middle\">HC#1007</td>");
		out.append("                      <td class=\"align-middle\">Đặng Ánh Nhật</td>");
		out.append("                      <td class=\"align-middle\">16/3/2025</td>");
		out.append("                      <td class=\"align-middle\">350000đ</td>");
		out.append("                      <td class=\"align-middle\">");
		out.append("                        <span class=\"badge bg-warning text-dark p-2\">Đang giao</span>");
		out.append("                      </td>");
		out.append("                      <td class=\"align-middle\">");
		out.append("                        <a href=\"../admin/single-order-view\"><i class=\"bi bi-eye fs-6 text-secondary ms-2 pointer\"></i></a>");
		out.append("");
		out.append("                        <i class=\"deleteIcon bi bi-trash fs-6 text-danger ms-2 pointer\"></i>");
		out.append("                      </td>");
		out.append("                    </tr>");
		out.append("");
		out.append("                  </tbody>");
		out.append("                </table>");
		out.append("                <!-- End Table with stripped rows -->");
		out.append("");
		out.append("              </div>");
		out.append("");
		out.append("              <!-- Nút Xuất dữ liệu -->");
		out.append("              <div class=\"d-flex justify-content-end mt-3\">");
		out.append("                <button type=\"button\" class=\"btn btn-primary\">");
		out.append("                  <i class=\"bi bi-download me-2\"></i> Xuất dữ liệu");
		out.append("                </button>");
		out.append("              </div>");
		out.append("");
		out.append("            </div>");
		out.append("          </div>");
		out.append("");
		out.append("        </div>");
		out.append("      </div>");
		out.append("    </section>");
		out.append("    <!-- thông báo -->");
		out.append("    <div class=\"modal fade\" id=\"confirmDeleteModal\" tabindex=\"-1\" aria-labelledby=\"confirmDeleteLabel\"");
		out.append("      aria-hidden=\"true\">");
		out.append("      <div class=\"modal-dialog modal-sm animate__animated animate__fadeInDown\">");
		out.append("        <div class=\"modal-content shadow\">");
		out.append("          <div class=\"modal-header\">");
		out.append("            <h5 class=\"modal-title\" id=\"confirmDeleteLabel\">Xác nhận xoá</h5>");
		out.append("            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Đóng\"></button>");
		out.append("          </div>");
		out.append("          <div class=\"modal-body\">");
		out.append("            Bạn có chắc chắn muốn xoá đơn hàng này không?");
		out.append("          </div>");
		out.append("          <div class=\"modal-footer\">");
		out.append("            <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Huỷ</button>");
		out.append("            <button type=\"button\" class=\"btn btn-danger\" id=\"confirmDeleteBtn\">Xoá</button>");
		out.append("          </div>");
		out.append("        </div>");
		out.append("      </div>");
		out.append("    </div>");
		out.append("    <!-- end thông báo -->");
		out.append("  </main><!-- End #main -->");
		out.append("");

		RequestDispatcher footerDispatcher = request.getRequestDispatcher("/admin/footer-view");
		footerDispatcher.include(request, response);
	}

	
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}
