package servlet.admin.view;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet("/admin/products-view")
public class ProductsView extends HttpServlet {
	private static final long serialVersionUID = 1L;

	public ProductsView() {
		super();
	}

	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		response.setContentType("text/html; charset=UTF-8");
		response.setCharacterEncoding("UTF-8");

		PrintWriter out = response.getWriter();
		request.setAttribute("view", "list");
		RequestDispatcher headerDispatcher = request.getRequestDispatcher("/admin/header-view");
		headerDispatcher.include(request, response);

		out.append("<main id=\"main\" class=\"main\">");
		out.append("    <div class=\"pagetitle d-flex justify-content-between\">");
		out.append("      <h1>Sản phẩm</h1>");
		out.append("      <nav class=\"d-flex align-items-center\">");
		out.append("        <ol class=\"breadcrumb  mb-0\">");
		out.append("          <li class=\"breadcrumb-item\"><a href=\"index.html\"><i class=\"bi bi-house-fill\"></i></a></li>");
		out.append("          <li class=\"breadcrumb-item active\">Sản phẩm</li>");
		out.append("        </ol>");
		out.append("      </nav>");
		out.append("    </div><!-- End Page Title -->");
		
		out.append("    <section class=\"section dashboard\">");
		out.append("      <div class=\"row product\">");
		out.append("        <div class=\"col-9 mt-4\">");
		out.append("          <div class=\"row\" style=\"background-color: #f5f8fe;\">");
		out.append("            <div class=\"col-xl-4 mb-3\">");
		out.append("              <div class=\"product__item\">");
		out.append("                <div class=\"product__item-img\">");
		out.append("                  <img");
		out.append("                    src=\"../admin/img/pro_nau_noi_that_moho_tu_quan_ao_1m2_5_2ea03038e88c4fa5bdd65d40a2787408_large.webp\"");
		out.append("                    alt=\"\">");
		out.append("                </div>");
		out.append("                <div class=\"product__item-name\">");
		out.append("                  Tủ Quần Áo Gỗ Có Gương MOHO GRENAA 2 Nhiều Kích Thước");
		out.append("                </div>");
		out.append("                <div class=\"product__item-price d-flex align-items-center\">");
		out.append("                  <div class=\"product__item-price-new\">4500000đ</div>");
		out.append("                  <div class=\"product__item-price_old ms-2\">5000000 VNĐ</div>");
		out.append("                </div>");
		out.append("                <div class=\"product__item-li\">");
		out.append("                  <span>Chất liệu:</span>");
		out.append("                  Gỗ công nghiệp chuẩn MDF");
		out.append("                </div>");
		out.append("                <div class=\"product__item-li\">");
		out.append("                  <span>Nhãn hiệu:</span>");
		out.append("                  MoHo");
		out.append("                </div>");
		out.append("                <div class=\"product__item-li\">");
		out.append("                  <span>Danh mục:</span>");
		out.append("                  Bàn");
		out.append("                </div>");
		out.append("                <div class=\"product__item-li\">");
		out.append("                  <span>Kích thước:</span>");
		out.append("                  H75 x W180 x D90 cm");
		out.append("                </div>");
		out.append("                <div class=\"product__item-color d-flex align-items-center\">");
		out.append("                  <span>Màu sắc:</span>");
		out.append("                  <button class=\"color-img ms-3 color-img-1\"></button>");
		out.append("                  <button class=\"color-img ms-2 color-img-2\"></button>");
		out.append("                </div>");
		out.append("                <div class=\"product__item-button d-flex justify-content-center mt-3\">");
		out.append("                  <a href=\"#\" class=\"view me-2\" title=\"Xem chi tiết\"><i class=\"bi bi-eye\"></i></a>");
		out.append("                  <a href=\"#\" class=\"edit me-2\" title=\"Sửa\"><i class=\"bi bi-pencil\"></i></a>");
		out.append("                  <a href=\"#\" class=\"delete me-2\" title=\"Xóa\"><i class=\"bi bi-trash\"></i></a>");
		out.append("                </div>");
		out.append("              </div>");
		out.append("            </div>");
		out.append("            <div class=\"col-xl-4 mb-3\">");
		out.append("              <div class=\"product__item\">");
		out.append("                <div class=\"product__item-img\">");
		out.append("                  <img");
		out.append("                    src=\"../admin/img/pro_nau_noi_that_moho_tu_quan_ao_1m2_5_2ea03038e88c4fa5bdd65d40a2787408_large.webp\"");
		out.append("                    alt=\"\">");
		out.append("                </div>");
		out.append("                <div class=\"product__item-name\">");
		out.append("                  Tủ Quần Áo Gỗ Có Gương MOHO GRENAA 2 Nhiều Kích Thước");
		out.append("                </div>");
		out.append("                <div class=\"product__item-price d-flex align-items-center\">");
		out.append("                  <div class=\"product__item-price-new\">4500000đ</div>");
		out.append("                  <div class=\"product__item-price_old ms-2\">5000000 VNĐ</div>");
		out.append("                </div>");
		out.append("                <div class=\"product__item-li\">");
		out.append("                  <span>Chất liệu:</span>");
		out.append("                  Gỗ công nghiệp chuẩn MDF");
		out.append("                </div>");
		out.append("                <div class=\"product__item-li\">");
		out.append("                  <span>Nhãn hiệu:</span>");
		out.append("                  MoHo");
		out.append("                </div>");
		out.append("                <div class=\"product__item-li\">");
		out.append("                  <span>Danh mục:</span>");
		out.append("                  Bàn");
		out.append("                </div>");
		out.append("                <div class=\"product__item-li\">");
		out.append("                  <span>Kích thước:</span>");
		out.append("                  H75 x W180 x D90 cm");
		out.append("                </div>");
		out.append("                <div class=\"product__item-color d-flex align-items-center\">");
		out.append("                  <span>Màu sắc:</span>");
		out.append("                  <button class=\"color-img ms-3 color-img-1\"></button>");
		out.append("                  <button class=\"color-img ms-2 color-img-2\"></button>");
		out.append("                </div>");
		out.append("                <div class=\"product__item-button d-flex justify-content-center mt-3\">");
		out.append("                  <a href=\"#\" class=\"view me-2\" title=\"Xem chi tiết\"><i class=\"bi bi-eye\"></i></a>");
		out.append("                  <a href=\"#\" class=\"edit me-2\" title=\"Sửa\"><i class=\"bi bi-pencil\"></i></a>");
		out.append("                  <a href=\"#\" class=\"delete me-2\" title=\"Xóa\"><i class=\"bi bi-trash\"></i></a>");
		out.append("                </div>");
		out.append("              </div>");
		out.append("            </div>");
		out.append("            <div class=\"col-xl-4 mb-3\">");
		out.append("              <div class=\"product__item\">");
		out.append("                <div class=\"product__item-img\">");
		out.append("                  <img");
		out.append("                    src=\"../admin/img/pro_nau_noi_that_moho_tu_quan_ao_1m2_5_2ea03038e88c4fa5bdd65d40a2787408_large.webp\"");
		out.append("                    alt=\"\">");
		out.append("                </div>");
		out.append("                <div class=\"product__item-name\">");
		out.append("                  Tủ Quần Áo Gỗ Có Gương MOHO GRENAA 2 Nhiều Kích Thước");
		out.append("                </div>");
		out.append("                <div class=\"product__item-price d-flex align-items-center\">");
		out.append("                  <div class=\"product__item-price-new\">4500000đ</div>");
		out.append("                  <div class=\"product__item-price_old ms-2\">5000000 VNĐ</div>");
		out.append("                </div>");
		out.append("                <div class=\"product__item-li\">");
		out.append("                  <span>Chất liệu:</span>");
		out.append("                  Gỗ công nghiệp chuẩn MDF");
		out.append("                </div>");
		out.append("                <div class=\"product__item-li\">");
		out.append("                  <span>Nhãn hiệu:</span>");
		out.append("                  MoHo");
		out.append("                </div>");
		out.append("                <div class=\"product__item-li\">");
		out.append("                  <span>Danh mục:</span>");
		out.append("                  Bàn");
		out.append("                </div>");
		out.append("                <div class=\"product__item-li\">");
		out.append("                  <span>Kích thước:</span>");
		out.append("                  H75 x W180 x D90 cm");
		out.append("                </div>");
		out.append("                <div class=\"product__item-color d-flex align-items-center\">");
		out.append("                  <span>Màu sắc:</span>");
		out.append("                  <button class=\"color-img ms-3 color-img-1\"></button>");
		out.append("                  <button class=\"color-img ms-2 color-img-2\"></button>");
		out.append("                </div>");
		out.append("                <div class=\"product__item-button d-flex justify-content-center mt-3\">");
		out.append("                  <a href=\"#\" class=\"view me-2\" title=\"Xem chi tiết\"><i class=\"bi bi-eye\"></i></a>");
		out.append("                  <a href=\"#\" class=\"edit me-2\" title=\"Sửa\"><i class=\"bi bi-pencil\"></i></a>");
		out.append("                  <a href=\"#\" class=\"delete me-2\" title=\"Xóa\"><i class=\"bi bi-trash\"></i></a>");
		out.append("                </div>");
		out.append("              </div>");
		out.append("            </div>");
		out.append("            <div class=\"col-xl-4 mb-3\">");
		out.append("              <div class=\"product__item\">");
		out.append("                <div class=\"product__item-img\">");
		out.append("                  <img");
		out.append("                    src=\"../admin/img/pro_nau_noi_that_moho_tu_quan_ao_1m2_5_2ea03038e88c4fa5bdd65d40a2787408_large.webp\"");
		out.append("                    alt=\"\">");
		out.append("                </div>");
		out.append("                <div class=\"product__item-name\">");
		out.append("                  Tủ Quần Áo Gỗ Có Gương MOHO GRENAA 2 Nhiều Kích Thước");
		out.append("                </div>");
		out.append("                <div class=\"product__item-price d-flex align-items-center\">");
		out.append("                  <div class=\"product__item-price-new\">4500000đ</div>");
		out.append("                  <div class=\"product__item-price_old ms-2\">5000000 VNĐ</div>");
		out.append("                </div>");
		out.append("                <div class=\"product__item-li\">");
		out.append("                  <span>Chất liệu:</span>");
		out.append("                  Gỗ công nghiệp chuẩn MDF");
		out.append("                </div>");
		out.append("                <div class=\"product__item-li\">");
		out.append("                  <span>Nhãn hiệu:</span>");
		out.append("                  MoHo");
		out.append("                </div>");
		out.append("                <div class=\"product__item-li\">");
		out.append("                  <span>Danh mục:</span>");
		out.append("                  Bàn");
		out.append("                </div>");
		out.append("                <div class=\"product__item-li\">");
		out.append("                  <span>Kích thước:</span>");
		out.append("                  H75 x W180 x D90 cm");
		out.append("                </div>");
		out.append("                <div class=\"product__item-color d-flex align-items-center\">");
		out.append("                  <span>Màu sắc:</span>");
		out.append("                  <button class=\"color-img ms-3 color-img-1\"></button>");
		out.append("                  <button class=\"color-img ms-2 color-img-2\"></button>");
		out.append("                </div>");
		out.append("                <div class=\"product__item-button d-flex justify-content-center mt-3\">");
		out.append("                  <a href=\"#\" class=\"view me-2\" title=\"Xem chi tiết\"><i class=\"bi bi-eye\"></i></a>");
		out.append("                  <a href=\"#\" class=\"edit me-2\" title=\"Sửa\"><i class=\"bi bi-pencil\"></i></a>");
		out.append("                  <a href=\"#\" class=\"delete me-2\" title=\"Xóa\"><i class=\"bi bi-trash\"></i></a>");
		out.append("                </div>");
		out.append("              </div>");
		out.append("            </div>");
		out.append("          </div>");
		out.append("        </div>");
		out.append("        <div class=\"col-3 mt-4\">");
		out.append("          <div class=\"row card py-2\" style=\"background-color: #f5f8fe; position: sticky; top: 100px;\">");
		out.append("            <div class=\"container py-4 d-flex flex-column align-items-start gap-3\" style=\"max-width: 320px;\">");
		out.append("              <div class=\"d-flex align-items-center gap-2 filter-label\">");
		out.append("                <i class=\"bi bi-funnel-fill\"></i>");
		out.append("                <span>BỘ LỌC</span>");
		out.append("              </div>");
		out.append("              <select class=\"form-select\" aria-label=\"Danh mục\">");
		out.append("                <option selected>SẢN PHẨM NỔI BẬT</option>");
		out.append("                <option value=\"1\">Option 1</option>");
		out.append("                <option value=\"2\">Option 2</option>");
		out.append("              </select>");
		out.append("              <select class=\"form-select\" aria-label=\"Danh mục\">");
		out.append("                <option selected>DANH MỤC</option>");
		out.append("                <option value=\"1\">Option 1</option>");
		out.append("                <option value=\"2\">Option 2</option>");
		out.append("              </select>");
		out.append("              <select class=\"form-select\" aria-label=\"Giá sản phẩm\">");
		out.append("                <option selected>GIÁ SẢN PHẨM</option>");
		out.append("                <option value=\"1\">Option 1</option>");
		out.append("                <option value=\"2\">Option 2</option>");
		out.append("              </select>");
		out.append("              <div class=\"color-select\">");
		out.append("                <span>MÀU SẮC</span>");
		out.append("                <div class=\"color-container\">");
		out.append("                  <div class=\"color-box\" data-color=\"#1A1A2E\" style=\"background-color: #1A1A2E;\"");
		out.append("                    onclick=\"selectColor(this)\">");
		out.append("                    <span class=\"checkmark\">✔</span>");
		out.append("                  </div>");
		out.append("                  <div class=\"color-box\" data-color=\"#0A2E8F\" style=\"background-color: #0A2E8F;\"");
		out.append("                    onclick=\"selectColor(this)\">");
		out.append("                    <span class=\"checkmark\">✔</span>");
		out.append("                  </div>");
		out.append("                  <div class=\"color-box\" data-color=\"#6B48FF\" style=\"background-color: #6B48FF;\"");
		out.append("                    onclick=\"selectColor(this)\">");
		out.append("                    <span class=\"checkmark\">✔</span>");
		out.append("                  </div>");
		out.append("                  <div class=\"color-box\" data-color=\"#00C4B4\" style=\"background-color: #00C4B4;\"");
		out.append("                    onclick=\"selectColor(this)\">");
		out.append("                    <span class=\"checkmark\">✔</span>");
		out.append("                  </div>");
		out.append("                  <div class=\"color-box\" data-color=\"#00FF00\" style=\"background-color: #00FF00;\"");
		out.append("                    onclick=\"selectColor(this)\">");
		out.append("                    <span class=\"checkmark\">✔</span>");
		out.append("                  </div>");
		out.append("                  <div class=\"color-box\" data-color=\"#FF4040\" style=\"background-color: #FF4040;\"");
		out.append("                    onclick=\"selectColor(this)\">");
		out.append("                    <span class=\"checkmark\">✔</span>");
		out.append("                  </div>");
		out.append("                  <div class=\"color-box\" data-color=\"#FFA500\" style=\"background-color: #FFA500;\"");
		out.append("                    onclick=\"selectColor(this)\">");
		out.append("                    <span class=\"checkmark\">✔</span>");
		out.append("                  </div>");
		out.append("                </div>");
		out.append("              </div>");
		
		out.append("              <select class=\"form-select\" aria-label=\"Kích thước\">");
		out.append("                <option selected>KÍCH THƯỚC</option>");
		out.append("                <option value=\"1\">Option 1</option>");
		out.append("                <option value=\"2\">Option 2</option>");
		out.append("              </select>");
		out.append("              <button type=\"button\" class=\"btn-search\">TÌM KIẾM</button>");
		out.append("            </div>");
		out.append("          </div>");
		out.append("        </div>");
		out.append("    </section>");
		out.append("  </main>");

		RequestDispatcher footerDispatcher = request.getRequestDispatcher("/admin/footer-view");
		footerDispatcher.include(request, response);
	}

	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}
